-- 코드를 입력하세요
# SELECT a.CATEGORY, a.PRICE AS MAX_PRICE, a.PRODUCT_NAME FROM FOOD_PRODUCT a
# natural join (SELECT PRODUCT_NAME, MAX(PRICE) as m FROM FOOD_PRODUCT GROUP BY CATEGORY) b 
# where a.CATEGORY IN ('과자', '국', '김치', '식용유')
# ORDER BY MAX_PRICE DESC

SELECT CATEGORY, PRICE AS MAX_PRICE, PRODUCT_NAME
  FROM FOOD_PRODUCT
 WHERE PRICE IN (SELECT MAX(PRICE) FROM FOOD_PRODUCT GROUP BY CATEGORY)
   AND CATEGORY IN ('과자', '국', '김치', '식용유')
ORDER BY MAX_PRICE DESC